export default [
  {
    id: 1,
    image: "image1.png",
    cost: "$200",
    center: "Great Wall Of China",
    location: "Beijing, China",
    rating: "4.5",
    review: "2.2k",
  },
  {
    id: 2,
    image: "image2.png",
    cost: "$400",
    center: "Louvre Museum",
    location: "Paris, ile-de-France, Franceosia",
    rating: "4.5",
    review: "1.6k",
  },
  {
    id: 3,
    image: "image3.png",
    cost: "$540",
    center: "Safdarjung Tomb",
    location: "New Delhi, DL, India",
    rating: "4.5",
    review: "3.6k",
  },
  {
    id: 4,
    image: "image4.png",
    cost: "$720",
    center: "Anitkabir Monument",
    location: "Ankara, Turkey",
    rating: "4.5",
    review: "4k",
  },
  {
    id: 5,
    image: "image5.png",
    cost: "$350",
    center: "Trevi Fountain",
    location: "Roma, Lazio, Italy",
    rating: "4.5",
    review: "5.2k",
  },
  {
    id: 6,
    image: "image6.png",
    cost: "$840",
    center: "Brown Concrete Tower",
    location: "Mexico City, CDMX Mexico",
    rating: "4.5",
    review: "2.2k",
  },
];
